services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - kohoutek
      - mysql
      - mailpit
    depends_on:
      - redis
      - memcached

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'kohoutek-redis:/data'
    networks:
      - kohoutek
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  memcached:
    image: 'memcached:alpine'
    ports:
      - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
    networks:
      - kohoutek

networks:
  kohoutek:
    driver: bridge
  mysql:
    external: true
  mailpit:
    external: true

volumes:
  kohoutek-redis:
    driver: local
